const express = require("express");
const authRouter = express.Router();

authRouter.post("/login",async (req,res)=>{
  try{
const {emailId ,password} = req.body;
const user = await userModel.findOne({emailId:emailId});
if(!user){
  res.status(404).json({
    message:"invalid Credentials"
  })
}
const isMatch = await bcrpt.compare(password,user.password);
if(!isMatch){
  res.status(400).json({
    message:"Invalid Credentials"
  })
}
else{
  const token = user.getJWT()
  console.log(token);
  res.cookie("token",token,{expires:new Date(Date.now()+ 24*60*60*1000)})// it will set the cookie in the browser with the name token and the value of the token generated by the json web token. it will expire in 1 day .
  res.status(200).json({
    message:"login successful",
  })

}
  }catch(error){
    res.status(404).json({
      message:error.message
    })
  }
})