const express = require("express");
const authRouter = express.Router();

authRouter.post("/login",async (req,res)=>{
  try{
const {emailId ,password} = req.body;
const user = await userModel.findOne({emailId:emailId});
if(!user){
  res.status(404).json({
    message:"invalid Credentials"
  })
}
const isMatch = await bcrpt.compare(password,user.password);
if(!isMatch){
  res.status(400).json({
    message:"Invalid Credentials"
  })
}
else{
  const token = user.getJWT()
  console.log(token);
  res.cookie("token",token,{expires:new Date(Date.now()+ 24*60*60*1000)})// it will set the cookie in the browser with the name token and the value of the token generated by the json web token. it will expire in 1 day .
  res.status(200).json({
    message:"login successful",
  })

}
  }catch(error){
    res.status(404).json({
      message:error.message
    })
  }
})


// middleware for signup to check whether the user with this email is already exist
authRouter.post("/signUp", async (req, res, next) => {
  try {
    const data = req.body;
    const existingUser = await userModel.findOne({ emailId: data.emailId });
    if (existingUser) {
      res.status(400).json({
        message: "user with this email already exist",
      });
    } else {
      next();
    }
  } catch (error) {
    res.status(500).json({
      message: error.message,
    });
  }
});
authRouter.post("/signUp", async (req, res) => {
  try {
    const data = req.body;
     const {password}=data;
     const hashedPassword = await bcrpt.hash(password,10);
   const user =await userModel.create({
      firstName: data.firstName,
      lastName: data.lastName,
      emailId: data.emailId,
      age: data.age,
      password:hashedPassword,
      gender: data.gender,
      skills: data.skills,
      about:data.about,
      photoUrl:data.photoUrl,

    });
    res.status(200).json({
      message: "User created successfully",
      user:user,
    });
  } catch (error) {
    res.status(500).json({
      message: error.message,
    });
  }
});

// for logout
authRouter.post("/logout", (req, res) => {
  try {
    res.clearCookie("token");
    res.status(200).json({
      message: "logout successful",
    });
  }
    catch (error) {
    res.status(500).json({
      message: error.message,
    });
  }
});

module.exports = authRouter;