const express = require("express");
const authRouter = express.Router();
const userModel = require("../model/user");
const bcrpt = require("bcrypt");
const multer = require("multer")
const uploadImage = require("../service/storage.service");
const { userAuth,signupAuth} = require("../middleware/auth");

// for login api we will use json web token to send the user id to the client side in the form of token so that the client can use it to access the protected routes. it generates a token using the user id and the secret key which is stored in the environment variable. the token is then sent to the client side in the form of cookie so that the client can use it to access the protected routes.
authRouter.post("/login",async (req,res)=>{
  try{
const {emailId ,password} = req.body;
const user = await userModel.findOne({emailId:emailId});
if(!user){
 return res.status(401).json({
    message:"invalid Credentials"
  })
}
const isMatch = await bcrpt.compare(password,user.password);
if(!isMatch){
  return res.status(401).json({
    message:"Invalid Credentials"
  })
}
else{
  const token = user.getJWT()
  res.cookie("token",token,{expires:new Date(Date.now()+ 24*60*60*1000),
  })// it will set the cookie in the browser with the name token and the value of the token generated by the json web token. it will expire in 1 day .
  res.status(200).json({
    message:"login successful",
  })

}
  }catch(error){
    res.status(500).json({
      message:error.message
    })
  }
})

const upload = multer({
  storage:multer.memoryStorage(),
      limits:{
        fileSize:5*1024*1024 // 5mb
    }
})
authRouter.post("/signUp",upload.single("image"),signupAuth, async (req, res) => {
  try {
    const data = req.body;
    const image = req.file;
    if(!image){
      return res.status(400).json({
        message:"Image is required"
      })
    }
    const result = await uploadImage(image.buffer,image.originalname);
    if(result.error){
      return res.status(500).json({
        message:result.message
      })
    }
     const {password}=data;
     const hashedPassword = await bcrpt.hash(password,10);
   const user =await userModel.create({
      firstName: data.firstName,
      lastName: data.lastName,
      emailId: data.emailId,
      age: data.age,
      password:hashedPassword,
      gender: data.gender,
      skills: data.skills,
      about:data.about,
      photoUrl:result.url,

    });
    res.status(200).json({
      message: "User created successfully",
      user:user,
    });
  } catch (error) {
    res.status(500).json({
      message: error.message,
    });
  }
});

// for logout
authRouter.post("/logout", (req, res) => {
  try {
    res.clearCookie("token");
    res.status(200).json({
      message: "logout successful",
    });
  }
  catch (error) {
    res.status(500).json({
      message: error.message,
    });
  }
});

module.exports = authRouter;